services:
  - type: web
    name: baseball-schedule-manager
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start:render
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        value: your-super-secure-session-secret-change-this-in-production
      - key: CORS_ORIGIN
        value: "*"
    healthCheckPath: /
    autoDeploy: true
