services:
  - type: web
    name: baseball-schedule-manager
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.render.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /
    autoDeploy: true
